### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by AnderBiguri** [CambridgeCIA/LION#61]
- [x] `git submodule update --init --recursive` before conda env create
- [x] lets remove msd from the repo
- [x] aitomotools->LION
- [x] conda activate aitomotools -> conda activate lion
- [x] ODL not available (remove completely)

**Comment by fsherry** [comment]
When I create a fresh environment using `conda create -f env.yml`, the pip dependencies in `env.yml` (probably most interestingly ts_algorithms and LION itself) are not installed. This is because the clean environment does not come with pip (and pip is installed by pip, i.e. not conda, in this environment file). We could change this by installing pip with conda instead (so that pip is available). Then we could continue to have conda install LION or we could take it out of `env.yml` and have the install step with `pip install [-e] .` after creating the conda environment (as in the current instructions in the README).

https://github.com/CambridgeCIA/LION/blob/7a8d44b2c47c66d3879c1fc3e74006f94cce9c7d/env.yml#L300-L313

**Comment by AnderBiguri** [comment]
@fsherry Yup, this env file must be changed. I think its still good to have a yml that is a dump of a working env, but, but 80% of the things listed on it are dependencies of dependencies, that we don't necessarily need to be explicit about. I'd suggest that what we need is just a simpler `yml` file, and indeed one that comes with pip. 

I haven't actively tackled this yet because I am unsure if we will need more dependencies down the line, but it may be a thing to do now that there are few people working with LION admitedly....
